#!/bin/bash

git add .
echo 'Enter commit message: '
read comment
git commit -m "$comment"

#git push
branch=$(git branch | cut -c3- | dmenu -p "Select the branch to push: ")
git push origin $branch

# push without login each time (use ssh):
# https://help.github.com/articles/connecting-to-github-with-ssh/

# set git to use ssh defaulut:
# git config --global url.ssh://git@github.com/.insteadOf https://github.com/
# (http://stackoverflow.com/questions/11200237/how-do-i-get-git-to-default-to-ssh-and-not-https-for-new-repositories)
# 
